---
title: "System drift and speciation in an oscillator"
author: "Joshua S. Schiffman and Peter L. Ralph"
date: "9/1/2021"
output: html_document
---

This code reproduces plots for panels in Figures 1, 2, 5 and 6 in _System drift and speciation_. 

```{r, echo=FALSE}
library(expm)
library(parallel)
library(grid)
library(gridExtra)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(cowplot)
library(grDevices)
```

```{r}
# Oscillator code

# A0, B and C correspond to the matrices of system coefficients described in Example 1.
A0 <- matrix(c(0,-1,1,0), nrow=2)
B <- matrix(c(1,1), ncol=1)
C <- matrix(c(1,0), nrow=1)

# A_fn corresponds to the parameterization of phenotypically equivalent oscillators described in Example 2.
A_fn <- function (tau) { 
    matrix(c(tau/(tau+1), -(2*tau*(tau+1)+1)/(tau+1), 
             1/(tau+1), -tau/(tau+1)), nrow=2) 
}

tt <- seq(0,6*2*pi, length.out=500)

# h is the impulse response of A_fn(tau)
h <- function (t,tau=0,A=A_fn(tau)) {
    sapply(t, function (tt) C %*% expm(tt*A) %*% B) 
    }


# The 'F1' function averages two haploid systems to form a diploid F1 system.
F1 <- function (tau1,tau2) { (A_fn(tau1)+A_fn(tau2))/2 }

# Generates F2 hybrid systems.
get_F2s <- function(tau1, tau2) 
    {
        vc <- function(tau1, tau2, x, y) 
            {
                out <- c(A_fn(tau1)[x,y], A_fn(tau2)[x,y])
                return(out)
            }
        mlist <- list()
        count <- 1
        for (i in 1:2) 
            {
                for (j in 1:2) 
                    {
                        for (k in 1:2) 
                            {
                                for (l in 1:2)
                                    {
                                        mlist[[count]] <- matrix(c(vc(tau1, tau2, 1, 1)[i], vc(tau1, tau2, 2, 1)[j], vc(tau1, tau2, 1, 2)[k], vc(tau1, tau2, 2, 2)[l]),2,2)
count <- count + 1
                                    }
                            }
                }
            }
        f2list <- list()
        count2 <- 1
        for(i in 1:length(mlist)) 
            {
                for (j in 1:length(mlist))
                    {
                        f2list[[count2]] <- (mlist[[i]] + mlist[[j]])/2
                        count2 <- count2 + 1
                    }
            }
    return(unique(f2list))
}
```


```{r fig1and2, fig.width=2.5, fig.height=1.5, fig.align="center"}

# Plots shown in Figures 1 and 2.

# h.2 function used to visualize kryptotypic dynamics.
C2 <- matrix(c(0,1), nrow=1)
h.2 <- function (t,tau=0,A=A_fn(tau)) { 
    sapply(t, function (tt) C2 %*% expm(tt*A) %*% B)
    }

# Phenotype
hhf00 <- sapply( list(A_fn(0)), function (A) { sapply(tt, h, A=A) } )

# Kryptotypes
hh02 <- sapply( list(A_fn(0)), function (A) { sapply(tt, h.2, A=A) } )
hhn22 <- sapply( list(A_fn(-2)), function (A) { sapply(tt, h.2, A=A) } )

# Phenotypes shown in Figure 1.
#pdf(file="Figure1_phenotype_plot.pdf", width=2.5, height=1.5, pointsize=10)

par(mar=c(4.5, 4, 1, 1)+.1)
plot(tt, hhf00, type="l", lwd=2, ylab= expression("phenotype" ~ phi(t)), xlab="time t", col="steelblue4", ylim=c(-3,3), cex.lab=1)

#dev.off()

# Kryptotypes shown in Figure 2.
#pdf(file="Figure2_kryptotype_plot.pdf", width=2.5, height=1.5, pointsize=10)

par(mar=c(4.5, 4, 1, 1)+.1)
plot(tt, hhf00, type="l", lwd=2, ylab= expression("kryptotype" ~ kappa(t)), xlab="time t", col="steelblue4", ylim=c(-3,3), cex.lab=1)
lines(tt, hhn22, lwd=2, col="seagreen")
lines(tt, hh02, lwd=2, col="red4")

#dev.off()
```

```{r fig5, fig.align="center", fig.width=14, fig.height=10}

# Parental phenotypes shown in Figure 5.
hhf0 <- sapply( list(A_fn(0), A_fn(0)), function (A) { sapply(tt, h, A=A) } )

# F1 phenotypes between A_fn(tau=0) and A_fn(tau=epsilon) shown in Figure 5.
hhf1_1 <- sapply( list(A_fn(0), A_fn(0.01), F1(0, 0.01)), function (A) { sapply(tt, h, A=A) } )
hhf1_2 <- sapply( list(A_fn(0), A_fn(0.1), F1(0, 0.1)), function (A) { sapply(tt, h, A=A) } )
hhf1_3 <- sapply( list(A_fn(0), A_fn(0.5), F1(0, 0.5)), function (A) { sapply(tt, h, A=A) } )

# F2 phenotypes between A_fn(tau=0) and A_fn(tau=epsilon) shown in Figure 5.
hhf2_1 <- sapply( get_F2s(0, 0.01), function (A) { sapply(tt, h, A=A) } )
hhf2_2 <- sapply( get_F2s(0, 0.1), function (A) { sapply(tt, h, A=A) } )
hhf2_3 <- sapply( get_F2s(0, 0.5), function (A) { sapply(tt, h, A=A) } )

```

```{r fig5plots, fig.width=14, fig.height=10}

# Figure 5 plots

cf <- colorRampPalette(colors = c("grey", "steelblue"))
hx <- data.frame("value"=hhf0[,1], "time"=tt, "variable"="parent")

# F1s 

k <- data.frame(hhf1_1)
k$time <- tt
pl11 <- (melt(k, id.vars = "time")) %>% ggplot(aes(x=time, y=value, group=variable, col=variable)) + 
    geom_line(size=0.25) + theme_classic(12) + theme(legend.position = "none") + 
    scale_color_manual(values = cf(3)) + ylim(c(-6,6)) + xlab("") + ylab("") +
    geom_line(data=hx, aes(x=time, y=value), color="black", size=0.5) + 
    annotate(geom = "text", label=expression(paste(epsilon, " = 0.01")), x=0, y=6, hjust=0, vjust=1, size=3)

k <- data.frame(hhf1_2)
k$time <- tt
pl12 <- (melt(k, id.vars = "time")) %>% ggplot(aes(x=time, y=value, group=variable, col=variable)) + 
    geom_line(size=0.25) + theme_classic(12) + theme(legend.position = "none") + 
    scale_color_manual(values = cf(3)) + ylim(c(-6,6)) + xlab("") + ylab("") + 
    geom_line(data=hx, aes(x=time, y=value), color="black", size=0.5) + 
    annotate(geom = "text", label=expression(paste(epsilon, " = 0.1")), x=0, y=6, hjust=0, vjust=1, size=3)

k <- data.frame(hhf1_3)
k$time <- tt
pl13 <- (melt(k, id.vars = "time")) %>% ggplot(aes(x=time, y=value, group=variable, col=variable)) + 
    geom_line(size=0.25) + theme_classic(12) + theme(legend.position = "none") + 
    scale_color_manual(values = cf(3)) + ylim(c(-6,6)) + xlab("") + ylab("") +
    geom_line(data=hx, aes(x=time, y=value), color="black", size=0.5) + 
    annotate(geom = "text", label=expression(paste(epsilon, " = 0.5")), x=0, y=6, hjust=0, vjust=1, size=3)

# F2s 
k <- data.frame(hhf2_1)
k$time <- tt
pl21 <- (melt(k, id.vars = "time")) %>% ggplot(aes(x=time, y=value, group=variable, col=variable)) + 
    geom_line(size=0.25) + theme_classic(12) + theme(legend.position = "none") + 
    scale_color_manual(values = cf(81)) + ylim(c(-6,6)) + xlab("") + ylab("") +
    geom_line(data=hx, aes(x=time, y=value), color="black", size=0.5) + 
    annotate(geom = "text", label=expression(paste(epsilon, " = 0.01")), x=0, y=6, hjust=0, vjust=1, size=3)

k <- data.frame(hhf2_2)
k$time <- tt
pl22 <- (melt(k, id.vars = "time")) %>% ggplot(aes(x=time, y=value, group=variable, col=variable)) + 
    geom_line(size=0.25) + theme_classic(12) + theme(legend.position = "none") + 
    scale_color_manual(values = cf(81)) + ylim(c(-6,6)) + xlab("") + ylab("") +
    geom_line(data=hx, aes(x=time, y=value), color="black", size=0.5) + 
    annotate(geom = "text", label=expression(paste(epsilon, " = 0.1")), x=0, y=6, hjust=0, vjust=1, size=3)

k <- data.frame(hhf2_3)
k$time <- tt
pl23 <- (melt(k, id.vars = "time")) %>% ggplot(aes(x=time, y=value, group=variable, col=variable)) + 
    geom_line(size=0.25) + theme_classic(12) + theme(legend.position = "none") + 
    scale_color_manual(values = cf(81)) + ylim(c(-6,6)) + xlab("") + ylab("") +
    geom_line(data=hx, aes(x=time, y=value), color="black", size=0.5) + 
    annotate(geom = "text", label=expression(paste(epsilon, " = 0.5")), x=0, y=6, hjust=0, vjust=1, size=3)

tr.grob <- textGrob(bquote(F[2]), 
                    gp=gpar(fontface="bold", col="black", fontsize=16))
tl.grob <- textGrob(bquote(F[1]), 
                    gp=gpar(fontface="bold", col="black", fontsize=16))
x.grob <- textGrob("time", 
                   gp=gpar(col="black", fontsize=12))
y.grob <- textGrob("phenotype", 
                   gp=gpar(col="black", fontsize=12), rot = 90)

k1 <- plot_grid(pl11, pl12, pl13, ncol=1)
k2 <- plot_grid(pl21, pl22, pl23, ncol=1)

k11 <- arrangeGrob(k1, top=tl.grob)
k22 <- arrangeGrob(k2, top=tr.grob)

k0 <- plot_grid(k11, k22, nrow = 1)

k00 <- arrangeGrob(k0, bottom=x.grob, left=y.grob)
out5 <- ggdraw(k00)
out5

#ggsave(out5, width=14, height=10, dpi=1000, filename="Figure5_hybrid_oscillators.pdf", scale=0.5)

```


```{r fig6, fig.align="center", fig.width=5, fig.height=3, cache=TRUE}

# Code for Figure 6

# Optimal impulse response function for the oscillator
optimal_h <- function (t) { 
    sin(t) + cos(t) 
    }

# Weighted difference between h(t,A) and optimal; square of equation (5)
Df <- function (A,t) {
    exp(-t/(4*pi)) * ( h(t,A=A) - optimal_h(t) )^2
}

D <- function (A, upper=10, ...) {
    f <- function (t) { Df(A,t) }
    integrate(f, lower=0, upper=upper, ...)$value
}

# Get all F2s.
get_F2s_nonunique <- function(tau1, tau2) {
    vc <- function(tau1, tau2, x, y) {
    out <- c(A_fn(tau1)[x,y], A_fn(tau2)[x,y])
    return(out)
    }
    
    mlist <- list()
    count <- 1
    for (i in 1:2) {
        for (j in 1:2) {
            for (k in 1:2)
                for (l in 1:2) {
                    mlist[[count]] <- matrix(c(vc(tau1, tau2, 1, 1)[i], 
                                               vc(tau1, tau2, 2, 1)[j], 
                                               vc(tau1, tau2, 1, 2)[k], 
                                               vc(tau1, tau2, 2, 2)[l]),
                                             2,2)
                    count <- count + 1
                }
        }
    }

    f2list <- list()
    count2 <- 1
    
    for(i in 1:length(mlist)) {
        for (j in 1:length(mlist)) {
            f2list[[count2]] <- (mlist[[i]] + mlist[[j]])/2
            count2 <- count2 + 1
        }
    }
    return(f2list)
}

# Compute genetic distance as described in the caption of Figure 6.
sys_gen_dist <- function(d) {
    sgd <- sqrt( sum( (A_fn(0) - A_fn(0+d))^2 ) )
    return(sgd)
}

dvec <- seq(0, 0.5, length.out=20)

D_F1 <- sapply(dvec, function (dtau) {D(A=F1(tau1=0, tau2=0+dtau), upper = 10 )} )

D_F2 <- do.call(cbind, mclapply(dvec, function (dtau) {
F2s <- get_F2s_nonunique(0, 0+dtau)
sapply(F2s, D, upper=10 )
}, mc.cores=detectCores() ) )

#pdf(file="Figure6_plot.pdf", width=5, height=3, pointsize=10)

plot( sapply(dvec, sys_gen_dist), sqrt(D_F1), type='l', ylab="phenotype distance (D)", xlab="genetic distance", ylim=c(0, 2), lwd=3)
lines(sapply(dvec, sys_gen_dist), colMeans(sqrt(D_F2)), lty=1, type="l", ylim=c(0,2), col="steelblue4", lwd=3)
legend(0, 2, legend = c( expression(F[1]~"hybrids"), expression(F[2]~"hybrids")), lty=1, lwd=3, col=c("black", "steelblue4"))

#dev.off()

```






