---
title: "sd_fig5"
author: "Josh Schiffman"
date: "6/26/2020"
output: html_document
---


```{r}
library(expm)
# System drift Figure 5 plot

A0 <- matrix(c(0,-1,1,0), nrow=2)
B <- matrix(c(1,1), ncol=1)
C <- matrix(c(1,0), nrow=1)

A_fn <- function (tau) { 
    matrix(c(tau/(tau+1), -(2*tau*(tau+1)+1)/(tau+1), 
             1/(tau+1), -tau/(tau+1)), nrow=2) 
}

tt <- seq(0,6*2*pi, length.out=500)

h <- function (t,tau=0,A=A_fn(tau)) { sapply(t, function (tt) C %*% expm(tt*A) %*% B) }


F1 <- function (tau1,tau2) { (A_fn(tau1)+A_fn(tau2))/2 }

get_F2s <- function(tau1, tau2) 
    {
        vc <- function(tau1, tau2, x, y) 
            {
                out <- c(A_fn(tau1)[x,y], A_fn(tau2)[x,y])
                return(out)
            }
        mlist <- list()
        count <- 1
        for (i in 1:2) 
            {
                for (j in 1:2) 
                    {
                        for (k in 1:2) 
                            {
                                for (l in 1:2)
                                    {
                                        mlist[[count]] <- matrix(c(vc(tau1, tau2, 1, 1)[i], vc(tau1, tau2, 2, 1)[j], vc(tau1, tau2, 1, 2)[k], vc(tau1, tau2, 2, 2)[l]),2,2)
count <- count + 1
                                    }
                            }
                }
            }
        f2list <- list()
        count2 <- 1
        for(i in 1:length(mlist)) 
            {
                for (j in 1:length(mlist))
                    {
                        f2list[[count2]] <- (mlist[[i]] + mlist[[j]])/2
                        count2 <- count2 + 1
                    }
            }
    return(unique(f2list))
}


hhf0 <- sapply( list(A_fn(0), A_fn(0)), function (A) { sapply(tt, h, A=A) } )

hhf1_1 <- sapply( list(A_fn(0), A_fn(0.01), F1(0, 0.01)), function (A) { sapply(tt, h, A=A) } )
hhf1_2 <- sapply( list(A_fn(0), A_fn(0.1), F1(0, 0.1)), function (A) { sapply(tt, h, A=A) } )
hhf1_3 <- sapply( list(A_fn(0), A_fn(0.5), F1(0, 0.5)), function (A) { sapply(tt, h, A=A) } )

hhf2_1 <- sapply( get_F2s(0, 0.01), function (A) { sapply(tt, h, A=A) } )
hhf2_2 <- sapply( get_F2s(0, 0.1), function (A) { sapply(tt, h, A=A) } )
hhf2_3 <- sapply( get_F2s(0, 0.5), function (A) { sapply(tt, h, A=A) } )


```

```{r, fig.align="center", fig.width=14, fig.height=10}

par(mfrow=c(3,2))
matplot(tt, hhf1_1, type='l', xlab="time", ylab="phenotype h(t)", lwd=2, ylim=c(-6,6), col=c("blue", "black"), cex.lab=1.5)
matplot(tt, hhf2_1, type='l', xlab="time", ylab="phenotype h(t)", lty=1, lwd=2, ylim=c(-6,6), cex.lab=1.5)
matlines(tt, hhf0, type='l', xlab="time", ylab="phenotype h(t)", lty=1, ylim=c(-6,6), cex.lab=1.5, col="black", lwd=4)
matplot(tt, hhf1_2, type='l', xlab="time", ylab="phenotype h(t)", lwd=2, ylim=c(-6,6), col=c("blue", "black"), cex.lab=1.5)
matplot(tt, hhf2_2, type='l', xlab="time", ylab="phenotype h(t)", lty=1, lwd=2, ylim=c(-6,6), cex.lab=1.5)
matlines(tt, hhf0, type='l', xlab="time", ylab="phenotype h(t)", lty=1, ylim=c(-6,6), cex.lab=1.5, col="black", lwd=4)
matplot(tt, hhf1_3, type='l', xlab="time", ylab="phenotype h(t)", lwd=2, ylim=c(-6,6), col=c("blue", "black"), cex.lab=1.5)
matplot(tt, hhf2_3, type='l', xlab="time", ylab="phenotype h(t)", lty=1, lwd=2, ylim=c(-6,6), cex.lab=1.5)
matlines(tt, hhf0, type='l', xlab="time", ylab="phenotype h(t)", lty=1, ylim=c(-6,6), cex.lab=1.5, col="black", lwd=4)

```


```{r, fig.width=2.5, fig.height=1.5, fig.align="center"}

C2 <- matrix(c(0,1), nrow=1)
h.2 <- function (t,tau=0,A=A_fn(tau)) { sapply(t, function (tt) C2 %*% expm(tt*A) %*% B) }

hhf00 <- sapply( list(A_fn(0)), function (A) { sapply(tt, h, A=A) } )
hh02 <- sapply( list(A_fn(0)), function (A) { sapply(tt, h.2, A=A) } )
hhn22 <- sapply( list(A_fn(-2)), function (A) { sapply(tt, h.2, A=A) } )

par(mar=c(4.5, 4, 1, 1)+.1)
plot(tt, hhf00, type="l", lwd=2, ylab= expression("phenotype" ~ phi(t)), xlab="time t", col="steelblue4", ylim=c(-3,3), cex.lab=1)

par(mar=c(4.5, 4, 1, 1)+.1)
plot(tt, hhf00, type="l", lwd=2, ylab= expression("kryptotype" ~ kappa(t)), xlab="time t", col="steelblue4", ylim=c(-3,3), cex.lab=1)
lines(tt, hhn22, lwd=2, col="seagreen")
lines(tt, hh02, lwd=2, col="red4")
```

```{r fig6, fig.align="center", fig.width=5, fig.height=3, cache=TRUE}
library(parallel)

optimal_h <- function (t) { sin(t)+cos(t) }


Df <- function (A,t) {
    exp(-t/(4*pi)) * ( h(t,A=A) - optimal_h(t) )^2
}

D <- function (A, upper=10, ...) {
    f <- function (t) { Df(A,t) }
    integrate(f, lower=0, upper=upper, ...)$value
}

get_F2s_nonunique <- function(tau1, tau2) {
    vc <- function(tau1, tau2, x, y) {
    out <- c(A_fn(tau1)[x,y], A_fn(tau2)[x,y])
    return(out)
}
mlist <- list()
count <- 1
for (i in 1:2) {
    for (j in 1:2) {
        for (k in 1:2)
            for (l in 1:2) {
                mlist[[count]] <- matrix(c(vc(tau1, tau2, 1, 1)[i], vc(tau1, tau2, 2, 1)[j], vc(tau1, tau2, 1, 2)[k], vc(tau1, tau2, 2, 2)[l]),2,2)
                count <- count + 1
            }
    }
}

f2list <- list()
count2 <- 1
for(i in 1:length(mlist)) {
    for (j in 1:length(mlist)) {
        f2list[[count2]] <- (mlist[[i]] + mlist[[j]])/2
        count2 <- count2 + 1
    }
}
return(f2list)
}

sys_gen_dist <- function(d) {
    sgd <- sqrt( sum( (A_fn(0) - A_fn(0+d))^2 ) )
    return(sgd)
}

dvec <- seq(0, 0.5, length.out=20)

D_F1 <- sapply(dvec, function (dtau) {
D(A=F1(tau1=0, tau2=0+dtau), upper = 10 )
} )

D_F2 <- do.call(cbind, mclapply(dvec, function (dtau) {
F2s <- get_F2s_nonunique(0, 0+dtau)
sapply(F2s, D, upper=10 )
}, mc.cores=detectCores() ) )

plot( sapply(dvec, sys_gen_dist), sqrt(D_F1), type='l', ylab="phenotype distance (D)", xlab="genetic distance", ylim=c(0, 2), lwd=3)
lines(sapply(dvec, sys_gen_dist), colMeans(sqrt(D_F2)), lty=1, type="l", ylim=c(0,2), col="steelblue4", lwd=3)
legend(0, 2, legend = c( expression(F[1]~"hybrids"), expression(F[2]~"hybrids")), lty=1, lwd=3, col=c("black", "steelblue4"))


```






